import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex flex-row w-full h-full  justify-between">
        <div className="flex flex-row w-1/2  h-full bg-red-700 justify-start items-start">
          {/* <Image
        layout="fill"
        // width={50}
        objectFit="contain"
        src={"/img.png"}
        alt="unable to load image"
        fill={true}
      ></Image> */}
          <div className="flex flex-col pl-10 pt-4">
            <div className="text-9xl font-mono font-bold text-white">Todo</div>
            <div className="text-7xl font-serif font-bold text-white p-10 pl-24">
              Plan
            </div>
            <div className="text-8xl font-bold text-white p-4 pl-56">Do</div>
            <div className="text-8xl font-thin  text-white p-8">Done</div>
          </div>
        </div>
        {children}
      </div>
    </div>
  );
}
