import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { ReactQueryClientProvider } from "../hooks/reactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className="min-h-screen">
    //     <main className="flex flex-col justify-between h-screen">
    //       {/* <ReactQueryClientProvider> */}
    <div className="flex flex-col justify-between h-screen">
      <Header />
      <div className="container mx-auto h-full">{children}</div>
      <Footer />
    </div>
    //       {/* </ReactQueryClientProvider> */}
    //     </main>
    //   </body>
    // </html>
  );
}
