import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Header from "../components/header";
import Footer from "../components/footer";
import Home from "./page";
import { ReactQueryClientProvider } from "../hooks/reactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col justify-between h-screen">
      <div className="container mx-auto h-full">{children}</div>
    </div>
  );
}
