import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Home from "./(dashboard)/page";
import { ReactQueryClientProvider } from "./hooks/reactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <main className="flex flex-col justify-between h-screen">
          <ReactQueryClientProvider>
            {/* <div> */}
            {/* <Header /> */}
            {children}
            {/* </div> */}
            {/* <Footer /> */}
          </ReactQueryClientProvider>
        </main>
      </body>
    </html>
  );
}
