import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { ReactQueryClientProvider } from "./hooks/reactQueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools/production";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <main className="flex flex-col justify-between h-screen">
          <ReactQueryClientProvider>
            <ReactQueryDevtools />
            {/* <div> */}
            {/* <Header /> */}
            {children}
            {/* </div> */}
            {/* <Footer /> */}
          </ReactQueryClientProvider>
        </main>
      </body>
    </html>
  );
}
